title: Kevin Tuğra KALKAN # your name (or website title) here
logo: "/images/Screenshot_1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Selçuk Üniversitesi Bilgisayar Mühendisliği
  <br><br>
  TED Ankara Koleji Vakfı Özel Lisesi'nden mezun olduktan sonra Selçuk Üniversitesi'nde öğrenim gördüm. Son sınıf öğrencisi olarak kariyerimi daha çok oyun ve yazılım geliştirme, web programlama konularında yapmak istiyorum. Üniversiteden mezun olduktan sonra yüksek lisans yapmayı planlıyorum. 
  <br><br>
  
theme: jekyll-theme-minimal

